// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Articles struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalResults         string     `protobuf:"bytes,2,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	Articles             []*Article `protobuf:"bytes,3,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Articles) Reset()         { *m = Articles{} }
func (m *Articles) String() string { return proto.CompactTextString(m) }
func (*Articles) ProtoMessage()    {}
func (*Articles) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *Articles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Articles.Unmarshal(m, b)
}
func (m *Articles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Articles.Marshal(b, m, deterministic)
}
func (m *Articles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Articles.Merge(m, src)
}
func (m *Articles) XXX_Size() int {
	return xxx_messageInfo_Articles.Size(m)
}
func (m *Articles) XXX_DiscardUnknown() {
	xxx_messageInfo_Articles.DiscardUnknown(m)
}

var xxx_messageInfo_Articles proto.InternalMessageInfo

func (m *Articles) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Articles) GetTotalResults() string {
	if m != nil {
		return m.TotalResults
	}
	return ""
}

func (m *Articles) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type Article struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	UrlToImage           string   `protobuf:"bytes,6,opt,name=urlToImage,proto3" json:"urlToImage,omitempty"`
	PublishedAt          string   `protobuf:"bytes,7,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	Content              string   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Article) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Article) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Article) GetUrlToImage() string {
	if m != nil {
		return m.UrlToImage
	}
	return ""
}

func (m *Article) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Source struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{2}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Articles)(nil), "proto.Articles")
	proto.RegisterType((*Article)(nil), "proto.Article")
	proto.RegisterType((*Source)(nil), "proto.Source")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xdf, 0x76, 0xbb, 0xdb, 0xbe, 0xd3, 0x3f, 0xca, 0x20, 0x12, 0x7a, 0x90, 0xb2, 0xa0,
	0x14, 0x91, 0x1e, 0xea, 0xc5, 0x6b, 0x0f, 0x22, 0x5e, 0xb7, 0x7e, 0x81, 0x74, 0x77, 0x68, 0x03,
	0xe9, 0x66, 0x49, 0x26, 0x82, 0x5f, 0xda, 0xcf, 0x20, 0x4d, 0xa2, 0xb4, 0xa7, 0xcc, 0xf3, 0x7b,
	0x92, 0x79, 0x32, 0x03, 0x53, 0x69, 0x59, 0xd5, 0x9a, 0x56, 0x9d, 0x35, 0x6c, 0x30, 0x0f, 0xc7,
	0x7c, 0xba, 0xa7, 0x96, 0xac, 0xd4, 0x91, 0x96, 0x16, 0x46, 0x9b, 0x78, 0xcd, 0xe1, 0x2d, 0x14,
	0x8e, 0x25, 0x7b, 0x27, 0x7a, 0x8b, 0xde, 0xf2, 0x7f, 0x95, 0x14, 0x96, 0x30, 0x61, 0xc3, 0x52,
	0x57, 0xe4, 0xbc, 0x66, 0x27, 0xfa, 0xc1, 0xbd, 0x60, 0xf8, 0x08, 0xa3, 0x14, 0xe7, 0x44, 0xb6,
	0xc8, 0x96, 0xe3, 0xf5, 0x2c, 0x26, 0xac, 0x52, 0xfb, 0xea, 0xcf, 0x2f, 0xbf, 0x7b, 0x30, 0x4c,
	0x14, 0xef, 0xa1, 0x70, 0xc6, 0xdb, 0x9a, 0x42, 0xe6, 0x78, 0x3d, 0x4d, 0xaf, 0xb6, 0x01, 0x56,
	0xc9, 0x3c, 0x7d, 0x4d, 0x7a, 0x3e, 0x18, 0x9b, 0xc2, 0x93, 0xc2, 0x1b, 0xc8, 0x59, 0xb1, 0x26,
	0x91, 0x05, 0x1c, 0x05, 0x2e, 0x60, 0xdc, 0x90, 0xab, 0xad, 0xea, 0x58, 0x99, 0x56, 0x0c, 0x82,
	0x77, 0x8e, 0xf0, 0x1a, 0x32, 0x6f, 0xb5, 0xc8, 0x83, 0x73, 0x2a, 0xf1, 0x0e, 0xc0, 0x5b, 0xfd,
	0x61, 0xde, 0x8f, 0x72, 0x4f, 0xa2, 0x08, 0xc6, 0x19, 0x39, 0xf5, 0xec, 0xfc, 0x4e, 0x2b, 0x77,
	0xa0, 0x66, 0xc3, 0x62, 0x18, 0x7b, 0x9e, 0x21, 0x14, 0x30, 0xac, 0x4d, 0xcb, 0xd4, 0xb2, 0x18,
	0x05, 0xf7, 0x57, 0x96, 0x4f, 0x50, 0xc4, 0x79, 0x70, 0x06, 0x7d, 0xd5, 0x84, 0x51, 0xf3, 0xaa,
	0xaf, 0x1a, 0x44, 0x18, 0xb4, 0xf2, 0x48, 0x69, 0xaa, 0x50, 0xaf, 0x5f, 0x60, 0x96, 0xb6, 0xb3,
	0x25, 0xfb, 0xa9, 0x6a, 0xc2, 0x07, 0xc8, 0xde, 0x88, 0x71, 0x92, 0x76, 0xf3, 0x7a, 0xec, 0xf8,
	0x6b, 0x7e, 0x75, 0xb9, 0x5f, 0x57, 0xfe, 0xdb, 0x15, 0x81, 0x3c, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x17, 0x8b, 0x28, 0x05, 0xfa, 0x01, 0x00, 0x00,
}
